### ISSUE TITLE
Missing charts in post_charts table

### ISSUE THREAD

**Issue by Marigold** [owid/owid-datasette#2]
This is probably a minor thing, but in case there are blocks in the content (references with `<!-- wp:block {"ref":24542} /-->`) like in https://ourworldindata.org/world-population-growth#population-growth, then those charts won't be in `post_charts` table. To fix this we'd have to lookup all references and materialize them in `content` before searching for links.
(This has been fixed in analytics repo)

**Comment by danyx23** [comment]
Nice catch, thank you! In the medium term we should probably move this kind of extraction to the level of the baking process where we have a richer model of our content

**Comment by danyx23** [comment]
@Marigold can you point me to the place where this is done in the analytics repo?

**Comment by danyx23** [comment]
Never mind, I found it - sorry for the ping :)

**Comment by marcelgerber** [comment]
I think this can be closed right? Since we now resolve WP reusable blocks at some other time in the process already, afaik?
@danyx23

**Comment by danyx23** [comment]
@marcelgerber yes true - for reference, we do this in both the syncPostsToGrapher file and the postUpdatedHook. The core logic for is here: https://github.com/owid/owid-grapher/blob/4a9c8bf7c32f73c85f4301adde84425744995630/db/syncPostsToGrapher.ts#L11-L102
