### ISSUE TITLE
Public SQLite Access

### ISSUE THREAD

**Issue by davidgasquez** [owid/owid-datasette#25]
Hey there!

Was trying to play with the public SQLite database of OWID and couldn't find it. 

I've tried these two `URI`s:

- `s3://owid-public/owid-public.sqlite.gz`
- `s3://owid-public/owid.db.gz`

**Comment by lucasrodes** [comment]
maybe @danyx23 knows?

**Comment by marcelgerber** [comment]
Hi!
You can find the public file at https://files.ourworldindata.org/owid-public.sqlite.gz.

**Comment by davidgasquez** [comment]
Thanks so much! Works perfectly. Should I send a small PR and surface the link into the README?
